name: flight_to_mars
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  email_validator: ^2.0.1
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  cloud_firestore: ^2.1.0
  flutter_spinkit: "^5.0.0"
  confetti: "^0.5.4+1"
  dropdown_formfield: "^0.1.3"
  firebase_storage: ^8.0.6
  image_picker: "^0.7.4"
  http: "^0.13.0"
  sms_autofill: ^2.0.0
  mailto: ^2.0.0
  url_launcher: ^6.0.3
  country_picker: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/mars_base.jpg
    - assets/images/pd.jpg
    - assets/images/green-tick.png

  fonts:
    - family: Oswald
      fonts:
        - asset: assets\fonts\Oswald-VariableFont_wght.ttf
    - family: Roboto-Condensed
      fonts:
        - asset: assets\fonts\RobotoCondensed-Bold.ttf
        - asset: assets\fonts\RobotoCondensed-Regular.ttf
    - family: Antonio
      fonts:
        - asset: assets\fonts\Antonio-VariableFont_wght.ttf
